### ISSUE TITLE
Owner of a group

### ISSUE THREAD

**Issue by slavizh** [microsoftgraph/msgraph-bicep-types#114]
**Bicep version**
Bicep CLI version 0.27.1 (4b41cb6d4b)

**Resource and API version**
Microsoft.Graph/groups@v1.0

**Auth flow**
automated

**Deployment details**
N/A

**Describe the bug**
When you create Microsoft365 group with application it lists the Microsoft Graph Bicep extension as owner. Preferably owner should be the application that did the deployment.

![image](https://github.com/microsoftgraph/msgraph-bicep-types/assets/11890856/8cae8d68-0c90-4be2-aff8-6f0b92e92eea)

**To Reproduce**
Create Microsoft365 group with application.

**Additional context**
Add any other context about the problem here. For example, what permissions does the identity have if it's a permission issue?

**Comment by dkershaw10** [comment]
@slavizh [Known issues has been updated](https://learn.microsoft.com/graph/templates/known-issues-graph-bicep#deployment-issue-app-only-deploy-of-microsoft-entra-groups-sets-the-wrong-owner) - with temporary workaround.  That said, we will work on getting a fix for this.

**Comment by eketo-msft** [comment]
Hey @slavizh, the bug has been identified and the fix is in progress.  Including the deployment time, it will probably take 2-3 weeks to get the fix shipped.  Happy to share any other details as needed.

**Comment by eketo-msft** [comment]
Just sharing an update.  The fix has been merged into the repo and we're expecting ~2 weeks for the deployment to complete.  I'll circle back here after deployment and verification is completed.

**Comment by eketo-msft** [comment]
Hey @slavizh, the fix for this is fully deployed and verified.  Please let me know if you continue to see any issues regarding group owner.

**Comment by dkershaw10** [comment]
Hi @slavizh - would you be able to verify the fix here please, and let us know if you are still seeing any issues?  Thanks in advance.

**Comment by danstis** [comment]
@dkershaw10 - As this item was linked to #134, should any application created also be automatically owned by the SP that created it? As we are still seeing no owner assigned to Applications created using the graph extension.

**Comment by dkershaw10** [comment]
@danstis So this should work for groups and service principals (ownership should be assigned for these resource types), but we do indeed still have a problem with applications that we are trying to nail down and fix.

**Comment by slavizh** [comment]
@dkershaw10 confirming that this is now fixed and the owner assigned now is the SP that was used for the deployment of the Microsoft 365 group.

![image](https://github.com/user-attachments/assets/04525689-5e7a-4d3e-b1a9-93cd405d437d)

**Comment by dkershaw10** [comment]
Just to confirm for others.  This is working for group ownership only.  We currently still have a bug for application ownership. We think we have a fix for this, and we're waiting for the rollout of the fix to start (which we will also verify in early integration rings).  We'll track status and validation of this issue in #134
