### ISSUE TITLE
Referencing Container App System Assigned Managed Identity fails validation

### ISSUE THREAD

**Issue by DavidMrLane** [microsoftgraph/msgraph-bicep-types#183]
**Bicep version**
 0.30.23

**Resource and API version**
Microsoft.Graph/groups@v1.0

**Auth flow**
Same errors on pipeline and when run manually

**Deployment details**
Fails at validation, before deployment

**Describe the bug**
Having  app.identity.principalId as a group member, produced the error:

Deployment template validation failed: 'The resource 'Microsoft.App/containerApps/providedAppName' is not defined in the template

When app.identity.principalId is removed/commented the template deploys, even though there are references to app.name

**To Reproduce**
This is my template:

extension microsoftGraph

param appName string
param appNameInitMiName string

resource app 'Microsoft.App/containerApps@2024-02-02-preview' existing = {
    name: appName
}
resource appInitMi 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' existing = {
    name: appNameInitMiName
}

resource schemaDataOperator 'Microsoft.Graph/groups@v1.0' = {
    displayName: 'Azure-${app.name}-dataOperator'
    mailEnabled: false
    mailNickname: guid('Azure-${app.name}-dataOperator')
    securityEnabled: true
    uniqueName: 'Azure-${app.name}-dataOperator'
    members: [
        appInitMi.properties.principalId
        app.identity.principalId
    ]
}
resource schemaDdlAdmin 'Microsoft.Graph/groups@v1.0' = {
    displayName: 'Azure-${app.name}-ddlAdmin'
    mailEnabled: false
    mailNickname: guid('Azure-${app.name}-ddlAdmin')
    securityEnabled: true
    uniqueName: 'Azure-${app.name}-ddlAdmin'
    members: [
        appInitMi.properties.principalId
    ]
}

**Comment by dkershaw10** [comment]
@DavidMrLane this seems the same as #178

**Comment by DavidMrLane** [comment]
yes you're correct. Adding an output statement allowed it to deploy, and removing it causes the validation to fail again.

**Comment by dkershaw10** [comment]
Very weird.

**Comment by shenglol** [comment]
This is odd, but it might be a bug in the deployment engine. I'll investigate this.

**Comment by shenglol** [comment]
Confirmed it's a bug. Working on a fix now.

**Comment by dkershaw10** [comment]
@shenglol any updates on this issue?

**Comment by shenglol** [comment]
Sorry for the late update, but the fix is deployed.

**Comment by dkershaw10** [comment]
Thanks! @DavidMrLane closing this issue - please feel free to reopen if you are still seeing this problem.

**Comment by DavidMrLane** [comment]
@dkershaw10 I'm still getting the same error. Now using bicep v0.32.4.

**Comment by dkershaw10** [comment]
@shenglol could you take another look at this please?
I'll see if I can repro this issue too.

**Comment by shenglol** [comment]
Apologies, the fix has not yet been fully deployed across all ARM regions due to the holiday deployment freeze. It may take a few more weeks to complete the rollout.

**Comment by dkershaw10** [comment]
@shenglol do we know if this has completed yet?

**Comment by gustyr** [comment]
hi, is there any update on this? @shenglol

**Comment by dkershaw10** [comment]
@gustyr - are you still seeing the same error? I would have thought that this deployment would have completed by now...

**Comment by DavidMrLane** [comment]
It looks to be working now.

**Comment by dkershaw10** [comment]
@DavidMrLane thanks for validating and closing.
